[package]
name = "verify_purchase"
type = "bin"
authors = ["Nikolay Kostadinov <nikolaykostadinov21@gmail.com>"]
compiler_version = ">=1.0.0"

[dependencies]
string_search = { tag = "v0.3.3", git = "https://github.com/noir-lang/noir_string_search" }
zkemail = { tag = "v.1.0.0-beta.5", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
